name: Test Email Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger
    inputs:
      test_message:
        description: 'Optional test message'
        required: false
        default: 'GitHub Actions Email Test'

jobs:
  test-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Email Configuration
      env:
        STOCK_EMAIL_SENDER: ${{ secrets.STOCK_EMAIL_SENDER }}
        STOCK_EMAIL_PASSWORD: ${{ secrets.STOCK_EMAIL_PASSWORD }}
        STOCK_EMAIL_RECEIVER: ${{ secrets.STOCK_EMAIL_RECEIVER }}
        GITHUB_EVENT: ${{ github.event_name }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        echo "🧪 Testing email configuration..."
        echo "📧 Event: $GITHUB_EVENT on branch $GITHUB_REF"
        echo "🔍 Commit: $GITHUB_SHA"
        echo "📤 This will send a test email to verify your setup"
        python test_email.py
        
    - name: Test Results
      if: always()
      run: |
        echo "📊 Email test completed!"
        echo "✅ If successful, you should receive a test email"
        echo "❌ If failed, check the logs above for error details"
